sudo: required
services:
  - docker

before_install:
  - docker build -t koehnden/frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true koehnden/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-230532572359"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"





